const express = require('express')
const { insertUser, deleteUser, getUser, updateUser } = require('../helpers/userHelper')
const { insertDriver, deleteDriver, getDrivers, updateDriver } = require('../helpers/driverHelper')
const { insertBus, deleteBus, getBuses, updateBus } = require('../helpers/busHelper')
const { insertMilestone, deleteMilestone, getMilestoneById, updateMilestone } = require('../helpers/milestoneHelper')
const { insertTrail, deleteTrail, getTrailById, updateTrail } = require('../helpers/trailHelper')
const { insertEvent, deleteEvent, getEvents, updateEvent } = require('../helpers/eventHelper')
const router = express.Router()
module.exports = router

router.post('/insertUser', insertUser)
router.delete('/deleteUser/:id', deleteUser)
router.post('/users', getUser)
router.patch('/updateUser', updateUser)

router.post('/insertDriver', insertDriver)
router.delete('/deleteDriver/:id', deleteDriver)
router.post('/drivers', getDrivers)
router.patch('/updateDriver', updateDriver)

router.post('/insertBus', insertBus)
router.delete('/deleteBus/:id', deleteBus)
// router.get('/buses/:id', getBusById)
router.post('/buses', getBuses)
// router.get('/busesByDriver', getBusesByDriver)
router.patch('/updateBus', updateBus)

router.post('/insertMilestone', insertMilestone)
router.delete('/deleteMilestone/:id', deleteMilestone)
router.get('/milestones/:id', getMilestoneById)
router.patch('/updateMilestone/:id', updateMilestone)

router.post('/insertTrail', insertTrail)
router.delete('/deleteTrail/:id', deleteTrail)
router.get('/trails/:id', getTrailById)
router.patch('/updateTrail/:id', updateTrail)

router.post('/insertEvent', insertEvent)
router.delete('/deleteEvent/:id', deleteEvent)
router.post('/events', getEvents)
// router.get('/events', getEventsByUser)
router.patch('/updateEvent', updateEvent)
